#!/usr/bin/env ansible-playbook
---
- name: Configure localhost
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Limit to Archlinux
      fail:
        msg: "{{ ansible_distribution }} is not supported."
      when: ansible_distribution != "Archlinux"

    - name: Display current hostname
      debug:
        msg: "The hostname is {{ ansible_hostname }}"

    - name: Update cache & upgrade system
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Include xorg
      include_tasks: xorg.yaml

    - name: Include alsa
      include_tasks: alsa.yaml
...
